### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by LohitakshTrehan** [LohitakshTrehan/RemindME#1]
The content.js needs addition of a Date picker, you can also work on other ui related improvements.

**Comment by KhushilMistry** [comment]
Hey, I want to contribute to this repo.
How can I start on Date Picker ?
also on running node server.js, its showing some error. What should I do ?

**Comment by LohitakshTrehan** [comment]
@KhushilMistry Thanks for your interest, so, to tell answer to your doubt, i will be updating the README.md file as early as possible, just wait a little

**Comment by KhushilMistry** [comment]
Cool. Update me after your changes. I will start work ASAP.

**Comment by LohitakshTrehan** [comment]
done @KhushilMistry

**Comment by anthonyFeDev** [comment]
I would like to see what other UI improvements i could make

**Comment by LohitakshTrehan** [comment]
Hi! @anthonyFeDev you can add Date selector, time selector, other ui improvements like: the box in which we fill list names closes as we press the '+' button. You can always try to modify UI as per your liking, if i like the change i will definitely merge it.
